#!/usr/bin/env bash
# Generate a Markdown index of all demos from their demo.yaml metadata.
# Usage: ./scripts/generate-index.sh > DEMOS.md
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "# Demo Index"
echo ""
echo "_Generated by \`scripts/generate-index.sh\`._"
echo ""
echo "| Name | Title | Category | Lifecycle | Maturity |"
echo "|---|---|---|---|---|"

find "$root/demos" -name 'demo.yaml' | sort | while IFS= read -r manifest; do
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$manifest" <<'PYEOF'
import sys, pathlib
try:
    import yaml
except ImportError:
    # fallback: basic grep-based extraction
    content = pathlib.Path(sys.argv[1]).read_text()
    name = next((l.split('name:')[1].strip() for l in content.splitlines() if '  name:' in l), '?')
    title = next((l.split('title:')[1].strip() for l in content.splitlines() if 'title:' in l), '?')
    print(f"| {name} | {title} | ? | ? | ? |")
    sys.exit(0)
data = yaml.safe_load(pathlib.Path(sys.argv[1]).read_text())
m = data.get('metadata', {})
s = data.get('spec', {})
print(f"| {m.get('name','?')} | {m.get('title','?')} | {s.get('category','?')} | {s.get('lifecycle','?')} | {s.get('maturity','?')} |")
PYEOF
  fi
done
